version: '3'

services: 
  postgres:
    image: postgres
    restart: always
    ports: 
      - "5433:5432"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=postgres
  web:
    image: nginx
    volumes:
    - ./templates:/etc/nginx/templates
    ports:
    - "90:80"
    environment:
    - NGINX_HOST=foobar.com
    - NGINX_PORT=80
    depends_on:
      - "postgres"